import { validateBundle } from "./validate";
import { deriveSortKey } from "./sort-key";
import { toPlainText } from "./publish";
import type { ActBundle } from "./schema";

export interface EmitOptions {
  reviewStatus: "draft" | "reviewed" | "published";
  publishAct: boolean;
  /** Sections per INSERT statement (keeps each statement reviewable/executable). */
  chunkSize?: number;
}

/** Dollar-quotes a text literal for SQL (bodies contain quotes freely). */
function q(text: string): string {
  if (text.includes("$nx$")) throw new Error("text contains dollar-quote tag");
  return `$nx$${text}$nx$`;
}

/**
 * Emits deterministic, reviewable SQL that mirrors publish.ts semantics:
 * act upsert by slug, chapter upserts by (act_id, number), section upserts by
 * (act_id, number) — PRESERVING section ids (bookmarks/mappings keep working).
 * Chunk boundaries are marked with `-- CHUNK` for batched execution.
 */
export function emitSql(bundle: ActBundle, options: EmitOptions): string {
  const { act, chapters, sections, provenance } = bundle;
  const chunkSize = options.chunkSize ?? 40;
  const lines: string[] = [];

  lines.push(`-- Generated by @nexlex/ingest emit-sql — act ${act.abbreviation} (${act.slug})`);
  lines.push(`-- provenance: ${provenance.replace(/\n/g, " ")}`);
  lines.push("-- CHUNK act");
  lines.push(`insert into public.acts (slug, title, short_title, abbreviation, year, category, status, enforcement_date, source_url${options.publishAct ? ", published_at" : ""})
values (${q(act.slug)}, ${q(act.title)}, ${act.shortTitle ? q(act.shortTitle) : "null"}, ${q(act.abbreviation)}, ${act.year}, ${q(act.category)}, ${q(act.status)}, ${act.enforcementDate ? q(act.enforcementDate) + "::date" : "null"}, ${q(act.sourceUrl)}${options.publishAct ? ", now()" : ""})
on conflict (slug) do update set
  title = excluded.title, short_title = excluded.short_title, year = excluded.year,
  category = excluded.category, status = excluded.status,
  enforcement_date = excluded.enforcement_date, source_url = excluded.source_url${options.publishAct ? ", published_at = coalesce(public.acts.published_at, excluded.published_at)" : ""};`);

  if (chapters.length > 0) {
    lines.push("-- CHUNK chapters");
    const values = chapters
      .map(
        (chapter) =>
          `((select id from public.acts where slug = ${q(act.slug)}), ${q(chapter.number)}, ${q(chapter.title)}, ${chapter.partNumber ? q(chapter.partNumber) : "null"}, ${chapter.partTitle ? q(chapter.partTitle) : "null"}, ${chapter.sortOrder})`,
      )
      .join(",\n  ");
    lines.push(`insert into public.act_chapters (act_id, number, title, part_number, part_title, sort_order)
values
  ${values}
on conflict (act_id, number) do update set
  title = excluded.title, part_number = excluded.part_number,
  part_title = excluded.part_title, sort_order = excluded.sort_order;`);
  }

  for (let i = 0; i < sections.length; i += chunkSize) {
    const chunk = sections.slice(i, i + chunkSize);
    lines.push(`-- CHUNK sections ${i + 1}-${i + chunk.length}`);
    const values = chunk
      .map((section) => {
        const chapterExpr = section.chapterNumber
          ? `(select id from public.act_chapters where act_id = (select id from public.acts where slug = ${q(act.slug)}) and number = ${q(section.chapterNumber)})`
          : "null";
        return `((select id from public.acts where slug = ${q(act.slug)}), ${chapterExpr}, ${q(section.number)}, ${deriveSortKey(section.number)}, ${q(section.marginalNote)}, ${q(section.bodyMd)}, ${q(section.bodyPlain ?? toPlainText(section.bodyMd))}, ${section.isRepealed ?? false}, ${section.effectiveFrom ? q(section.effectiveFrom) + "::date" : "null"}, ${q(options.reviewStatus)}, ${q(provenance)})`;
      })
      .join(",\n  ");
    lines.push(`insert into public.act_sections (act_id, chapter_id, number, sort_key, marginal_note, body_md, body_plain, is_repealed, effective_from, review_status, provenance)
values
  ${values}
on conflict (act_id, number) do update set
  chapter_id = excluded.chapter_id, sort_key = excluded.sort_key,
  marginal_note = excluded.marginal_note, body_md = excluded.body_md,
  body_plain = excluded.body_plain, is_repealed = excluded.is_repealed,
  effective_from = excluded.effective_from, review_status = excluded.review_status,
  provenance = excluded.provenance, version = public.act_sections.version + 1;`);
  }

  return lines.join("\n\n") + "\n";
}

export function emitSqlFromRaw(input: unknown, options: EmitOptions): string {
  const report = validateBundle(input);
  if (!report.ok || !report.bundle) {
    throw new Error(`bundle failed validation:\n${report.errors.join("\n")}`);
  }
  return emitSql(report.bundle, options);
}
